=== TheHugeManatee/MolSim/SimulationConfig.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xse="http://www.codesynthesis.com/xmlns/xml-schema-extension">

  <xsd:simpleType name="TransformType">
  	<xsd:restriction base="xsd:string">
  		<xsd:enumeration value="scale" />
  		<xsd:enumeration value="translate" />
  		<xsd:enumeration value="rotatex0" />
  		<xsd:enumeration value="rotatex1" />
      <xsd:enumeration value="rotatex2" />
      <xsd:enumeration value="shear" />
      <xsd:enumeration value="perspective" />
  	</xsd:restriction>
  </xsd:simpleType> 
       
  <xsd:complexType name="transform">
    <xsd:sequence>
      <xsd:element name="x" type="floatVector" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="type" type="TransformType" use="required" />
    <xsd:attribute name="angle" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear01" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear02" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear10" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear12" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear20" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear21" type="xsd:double" use="optional" default="0" />
  </xsd:complexType>
       
  <xsd:simpleType name="BoundaryConditionType">
  	<xsd:restriction base="xsd:string">
  		<xsd:enumeration value="Outflow" />
  		<xsd:enumeration value="Reflect" />
  		<xsd:enumeration value="Periodic" />
  	</xsd:restriction>
  </xsd:simpleType>    
        
  <xsd:simpleType name="OutputFileType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="xyz" />
      <xsd:enumeration value="vtk" />
    </xsd:restriction>
  </xsd:simpleType>
        
  <xsd:simpleType name="ScenarioType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Gravity"/>
      <xsd:enumeration value="Lennard-Jones"/>
      <xsd:enumeration value="Membrane"/>
      <xsd:enumeration value="Lennard-Jones-Smoothed"/>
</xsd:restriction>
  </xsd:simpleType>    
  
  <xsd:simpleType name="ThermostatSwitch">
  	<xsd:restriction base="xsd:string">
  		<xsd:enumeration value="ON"/>
  		<xsd:enumeration value="OFF"/> 
  	</xsd:restriction>
  </xsd:simpleType>		
  
  <xsd:simpleType name="ContainerType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ParticleContainer"/>
      <xsd:enumeration value="CellListContainer"/>
    </xsd:restriction>
  </xsd:simpleType>     
                       
  <xsd:complexType name="BoundaryHandlingType">
    <xsd:attribute name="right" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="left" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="top" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="bottom" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="front" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="back" type="BoundaryConditionType" use="required" />
  </xsd:complexType>
                            	
	<xsd:complexType name="floatVector">
		<xsd:attribute name="x0" type="xsd:double" use="required"/>
		<xsd:attribute name="x1" type="xsd:double" use="required"/>
		<xsd:attribute name="x2" type="xsd:double" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="intVector">
		<xsd:attribute name="x0" type="xsd:int" use="required"/>
		<xsd:attribute name="x1" type="xsd:int" use="required"/>
		<xsd:attribute name="x2" type="xsd:int" use="required"/>
	</xsd:complexType>   

	<xsd:complexType name="ParticleType">
	  <xsd:attribute name="mass" type="xsd:double" use="required" />
	  <xsd:attribute name="sigma" type="xsd:double" use ="required"/>
	  <xsd:attribute name="epsilon" type="xsd:double" use ="required"/>
	  <xsd:attribute name="isMolecule" type="xsd:boolean" use="optional" default="false" />
	  <xsd:attribute name="averageBondLength" type="xsd:double" use="optional" default="2.2" />
	  <xsd:attribute name="stiffness" type="xsd:double" use="optional" default="300" />
	  <xsd:attribute name="nX0" type="xsd:double" use="optional" default="1" />
	  <xsd:attribute name="nX1" type="xsd:double" use="optional" default="1" />
	  <xsd:attribute name="nX2" type="xsd:double" use="optional" default="1" />
	</xsd:complexType>

	<xsd:complexType name="cutOffRadius">
	  <xsd:attribute name="scaled" type="xsd:boolean" use="required"/>
	  <xsd:attribute name="radius" type="xsd:double" use="required"/>
	</xsd:complexType> 

	<xsd:complexType name ="TypesList">
	  <xsd:sequence>
	    <xsd:element name="particleType" type ="ParticleType" maxOccurs ="unbounded" minOccurs = "1"/>
	  </xsd:sequence>  
	</xsd:complexType> 

<xsd:complexType name="cuboid">
	  <xsd:sequence>
	  	<xsd:element name="bottomLeft" type="floatVector"/>
	  	<xsd:element name="nX" type="intVector" />
	  	<xsd:element name="stepWidth" type="xsd:double"/>
	  	<xsd:element name="type" type="xsd:int"/>
	  	<xsd:element name="initialVelocity" type="floatVector"/>
	  	<xsd:element name="brownianMeanVelocity" type="xsd:double" minOccurs="0" maxOccurs="1"/>
	  	<xsd:element name="transform" type="transform" minOccurs="0" maxOccurs="unbounded" />
	 </xsd:sequence>
  </xsd:complexType>

  
  <xsd:complexType name="sphere">
	  <xsd:sequence>
	  	<xsd:element name="center" type="floatVector"/>
	  	<xsd:element name="radius" type="xsd:int" />
	  	<xsd:element name="stepWidth" type="xsd:double"/>
	  	<xsd:element name="type" type="xsd:int"/>
	  	<xsd:element name="initialVelocity" type="floatVector"/>
	  	<xsd:element name="brownianMeanVelocity" type="xsd:double" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="transform" type="transform" minOccurs="0" maxOccurs="unbounded" />
	 </xsd:sequence>
  </xsd:complexType>

 <xsd:complexType name="cylinder">
	  <xsd:sequence>
	  	<xsd:element name="bottom" type="floatVector"/>
		<xsd:element name="height" type="xsd:int"/>
	  	<xsd:element name="radius" type="xsd:int"/>
	  	<xsd:element name="stepWidth" type="xsd:double"/>
	  	<xsd:element name="type" type="xsd:int"/>
	  	<xsd:element name="initialVelocity" type="floatVector"/>
	  	<xsd:element name="brownianMeanVelocity" type="xsd:double" minOccurs="0" maxOccurs="1"/>
	  	<xsd:element name="transform" type="transform" minOccurs="0" maxOccurs="unbounded" />
	 </xsd:sequence>
 </xsd:complexType>
            
  <xsd:complexType name="generator">
  	<xsd:sequence>
  		<xsd:element name="cuboid" type="cuboid" maxOccurs="unbounded"/>
  		<xsd:element name="sphere" type="sphere" maxOccurs="unbounded"/>
      <xsd:element name="cylinder" type="cylinder" maxOccurs="unbounded"/>
	</xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="ThermostatSettings">
    	<xsd:sequence>
  	  <xsd:element name="initTemperature" type="xsd:double" maxOccurs="1" minOccurs="0" />
  	  <xsd:element name="targetTemperature" type="xsd:double" minOccurs ="0" maxOccurs="1"/>
  	  <xsd:element name="controlInterval" type="xsd:int"/>
  	  <xsd:element name="estimatedSteps" type="xsd:int" minOccurs ="0" maxOccurs="1"/>
	  <xsd:element name="temperaturePerStep" type="xsd:double" minOccurs ="0" maxOccurs="1"/>
	  <xsd:element name="maxSteps" type="xsd:int" minOccurs ="0" maxOccurs="1"/>
	</xsd:sequence> 
 </xsd:complexType>

<xsd:complexType name="forceField">
  <xsd:sequence>
    <xsd:element name="type" type = "xsd:int"/>
    <xsd:element name="from" type="intVector"/>  
    <xsd:element name="to" type="intVector"/>
    <xsd:element name="force" type="floatVector"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="dummyForConstructors">
  <xsd:sequence>
    <xsd:element name="ThermostatSettings" type="ThermostatSettings"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="statistics">
  <xsd:attribute name="fileName" type="xsd:string" use="required" />
  <xsd:attribute name="interval" type="xsd:int" use="required" />  
  <xsd:attribute name="deltaR" type="xsd:double" use="required" />
</xsd:complexType>

<xsd:complexType name="simulationConfig">
    <xsd:sequence>
      <xsd:element name="deltaT" type="xsd:double"/>
      <xsd:element name="endTime" type="xsd:double"/>
      <xsd:element name="dimensions" type="xsd:int" minOccurs="0" maxOccurs="1"/> 
      <xsd:element name="scenarioType" type="ScenarioType"/>
      <xsd:element name="domainSize" type="floatVector" />
      <xsd:element name="cutoffRadius" type="cutOffRadius" />
      <xsd:element name="lRadius" type="xsd:double" minOccurs = "0" maxOccurs = "1"/>      
      <xsd:element name="boundaryHandling" type="BoundaryHandlingType" />
      <xsd:element name="containerType" type="ContainerType" />
      <xsd:element name="gravitation" type="floatVector" minOccurs ="0" maxOccurs="1"/>
      <xsd:element name="outputFrequency" type="xsd:int"/>
      <xsd:element name="disableOutput" type="xsd:boolean"/>
      <xsd:element name="loggerConfigFile" type="xsd:string"/>
      <xsd:element name="outputFilePrefix" type="xsd:string"/>
      <xsd:element name="outputFileIterationOffset" type="xsd:int" minOccurs="0" maxOccurs="1" />
      <xsd:element name="outputFileType" type="OutputFileType"/>
      <xsd:element name="saveLastState" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="inputFile" type="xsd:string" minOccurs ="0" maxOccurs="1"/>
      <xsd:element name="statistics" type="statistics" minOccurs="0" maxOccurs="1" />
      <xsd:element name="thermostatSwitch" type="ThermostatSwitch" minOccurs ="0" maxOccurs="1"/>
      <xsd:element name="thermostatSettings" type="ThermostatSettings" minOccurs ="0" maxOccurs="1"/>      
      <xsd:element name="typeList" type="TypesList" />
      <xsd:element name="forceField" type="forceField" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="generator" type="generator"/>
  </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="simulationConfig" type="simulationConfig" />

</xsd:schema>

=== TheHugeManatee/MolSim/simulationConfig.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
  <deltaT>0.0005</deltaT>
  <endTime>100</endTime>
  <dimensions>3</dimensions>
  <scenarioType>Membrane</scenarioType>
  <domainSize x0="60.0" x1="60.0" x2="30" />
  <cutoffRadius scaled="1" radius="3.0"/>

  <boundaryHandling
  	top="Reflect" bottom="Reflect"
  	left="Reflect" right="Reflect"
  	front="Reflect" back="Reflect"
  />
  
  <containerType>CelllistContainer</containerType>
  <epsilon>5</epsilon>
  <sigma>1</sigma>
  <gravitationConstant>0</gravitationConstant>
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/MD_vtk</outputFilePrefix>
  <outputFileType>vtk</outputFileType>
  
  <thermostatSwitch>OFF</thermostatSwitch>

<thermostatSettings>
	<initTemperature>40.0</initTemperature>
	<targetTemperature>40.0</targetTemperature>
  	<controlInterval>1000</controlInterval>
<!--<estimatedSteps>20000</estimatedSteps> -->
<!--<maxSteps>30000</maxSteps> -->
  </thermostatSettings>

 <typeList>
 	<particleType Nr="1" sigma="1.5" epsilon="1.0"/>
 	<particleType Nr="2" sigma="0.9412" epsilon="1.0"/>
 </typeList>  
 
 <generator>
 <!--	 <cuboid>
      <bottomLeft x0="10.0" x1="5.0" x2="10.0" />
      <nX x0="8" x1="8" x2="1" />
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="0" x2="0"/>
    </cuboid> -->
    
<sphere>
      <center x0="15" x1="15" x2="15" />
      <radius>1</radius>
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>2</type>
      <initialVelocity x0="0" x1="0" x2="-0.5"/>
	</sphere>
	
  <membrane>
   	<stiffnessConstant>300</stiffnessConstant>
   	<averageBondLength>2.2</averageBondLength>
  	<cuboid>
      <bottomLeft x0="10" x1="10" x2="4" />
      <nX x0="10" x1="10" x2="1" />
      <stepWidth>1.2</stepWidth>
      <mass>2.0</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="0" x2="0"/>
    </cuboid>
  </membrane>
	
<!--	 <cuboid>
      <bottomLeft x0="10.0" x1="15.0" x2="6.0" />
      <nX x0="10" x1="3" x2="1" />
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>2</type>
      <initialVelocity x0="0" x1="0" x2="0"/>
    </cuboid> -->
  </generator>
  

</simulationConfig>

=== TheHugeManatee/MolSim/sampleConfigs/sheet5_argon2.2.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
<!--(m): mandatory (o): optional-->     
  
  <deltaT>0.001</deltaT>
  <endTime>100</endTime>
  <dimensions>3</dimensions> <!-- (o) Standard is 3, For a two dimensionalSimulation all particles should have the same z value > 0  --> 
  <scenarioType>Lennard-Jones-Smoothed</scenarioType> <!-- (m) Possible: Gravitational, Lennard-Jones, Membrane  -->
  <domainSize x0="9.2" x1="9.2" x2="9.2" /><!-- (m) -->
  <cutoffRadius scaled="1" radius="2.3" /><!-- (m) scaled implies whether the radius is scaled by the greatest sigma value or not-->
  <lRadius>1.9</lRadius>
  <boundaryHandling
  	top="Periodic" bottom="Periodic"					
  	left="Periodic" right="Periodic"		
  	front="Periodic" back="Periodic"
  />
  
  <containerType>CellListContainer</containerType> <!-- (m) Possible: ParticleContainer , CelllistContainer -->
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/ArgonSuperCooling</outputFilePrefix>
  <outputFileType>vtk</outputFileType> 
  <saveLastState></saveLastState> <!--(o) for a given filePath the last state of the particles is saved (can be used as inputFile afterwards) -->
  <inputFile>argonliquid.state</inputFile> <!-- (o)  -->
  
  <thermostatSwitch>ON</thermostatSwitch> <!-- (o) Possible:ON , OFF indicates whether the given thermostat is used. is switched OFF if left out -->
  <thermostatSettings> <!-- (o) if left out thermostatSwitch is set OFF -->
  	<targetTemperature>0.02</targetTemperature>
  	<controlInterval>25</controlInterval>
    <temperaturePerStep>-0.0025</temperaturePerStep>
  
  </thermostatSettings>

  
 <typeList> <!-- (m) a List of types recognized by the particle generator for applying unique values for sigma and epsilon -->
 <particleType 
 		sigma="1" 
 		epsilon="1"
 		mass="1"  
 		/>
 </typeList>  
 
 <generator>
<!--  <cuboid>
    <bottomLeft x0="0.575" x1="0.575" x2="0.575" />
    <nX x0="8" x1="8" x2="8" />
    <stepWidth>1.15</stepWidth>
    <type>0</type>
    <initialVelocity x0="0" x1="0" x2="0"/>
  </cuboid> -->
</generator>

</simulationConfig>

=== TheHugeManatee/MolSim/sampleConfigs/sheet4_bench_big.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
  <deltaT>0.0005</deltaT>
  <endTime>50</endTime>
  <scenarioType>Lennard-Jones-Gravitational</scenarioType>
  <domainSize x0="300.0" x1="54.0" x2="7.5" />
  <cutoffRadius>2.5</cutoffRadius>

  <boundaryHandling
  	top="Reflect" bottom="Reflect"
  	left="Reflect" right="Reflect"
  	front="Reflect" back="Reflect"
  />
  
  <containerType>CelllistContainer</containerType>
  <epsilon>1</epsilon>
  <sigma>1</sigma>
  <gravitationConstant>-12.44</gravitationConstant>
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/MD_vtk</outputFilePrefix>
  <outputFileType>vtk</outputFileType>
  <inputFile></inputFile>
  
  <thermostatSwitch>ON</thermostatSwitch>

  <thermostatSettings>
  	<initTemperature>40.0</initTemperature>
  	<targetTemperature>40.0</targetTemperature>
  	<controlInterval>1000</controlInterval>
  	<estimatedSteps>300000</estimatedSteps>
  	<maxSteps>300000</maxSteps>
  </thermostatSettings>
  
 <typeList>
 <type Nr = "1" sigma = "1.2" epsilon = "1.0" />
 <type Nr = "2" sigma = "1.1" epsilon = "1.0" />
 </typeList>  
 
 <generator>
   <cuboid>
      <bottomLeft x0="0.6" x1="2.0" x2="3.75" />
      <nX x0="250" x1="20" x2="1" />
      <stepWidth>1.2</stepWidth>
      <mass>1.0</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="0" x2="0"/>
      <brownianMeanVelocity>0</brownianMeanVelocity>
      <sigma></sigma>
      <delta></delta>
    </cuboid>
    <cuboid>
      <bottomLeft x0="0.6" x1="27.0" x2="3.75" />
      <nX x0="250" x1="20" x2="1" />
      <stepWidth>1.2</stepWidth>
      <mass>2.0</mass>
      <type>2</type>
      <initialVelocity x0="0" x1="0" x2="0"/>
      <brownianMeanVelocity>0</brownianMeanVelocity>
	  <sigma></sigma>
      <delta></delta>      
    </cuboid>
  </generator>
  

</simulationConfig>

=== TheHugeManatee/MolSim/sampleConfigs/sheet3_bench.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
  <deltaT>0.0005</deltaT>
  <endTime>20</endTime>
  <scenarioType>Lennard-Jones</scenarioType>
  <domainSize x0="180.0" x1="90.0" x2="1.0" />
  <containerType>ParticleContainer</containerType>
  <epsilon>5</epsilon>
  <sigma>1</sigma>
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/MD_benchmark</outputFilePrefix>
  <outputFileType>vtk</outputFileType>
  <inputFile></inputFile>

  <generator>
   <cuboid>
      <bottomLeft x0="20.0" x1="20.0" x2="0.0" />
      <nX x0="100" x1="20" x2="1" />
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="0" x2="0"/>
      <brownianMeanVelocity>0.1</brownianMeanVelocity>
    </cuboid>
    <cuboid>
      <bottomLeft x0="70.0" x1="60.0" x2="0.0" />
      <nX x0="20" x1="20" x2="1" />
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>2</type>
      <initialVelocity x0="0" x1="-10" x2="0"/>
      <brownianMeanVelocity>0.1</brownianMeanVelocity>
    </cuboid>
    
  </generator>
  

</simulationConfig>

=== TheHugeManatee/MolSim/sampleConfigs/wall.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
  <deltaT>0.0005</deltaT>
  <endTime>20</endTime>
  <scenarioType>Lennard-Jones</scenarioType>
  <domainSize x0="80.0" x1="80.0" x2="1.0" />
  <boundaryHandling
  	top="Reflect" bottom="Reflect"
  	left="Reflect" right="Reflect"
  	front="Outflow" back="Outflow"
  />
  <containerType>CelllistContainer</containerType>
  <epsilon>5</epsilon>
  <sigma>1</sigma>
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/wall</outputFilePrefix>
  <outputFileType>vtk</outputFileType>
  <inputFile></inputFile>

  <generator>
    <cuboid>
      <bottomLeft x0="20.0" x1="20.0" x2="0" />
      <nX x0="20" x1="20" x2="1" />
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>2</type>
      <initialVelocity x0="30" x1="-10" x2="0"/>
      <brownianMeanVelocity>0.1</brownianMeanVelocity>
    </cuboid>
    
  </generator>
  

</simulationConfig>

=== TheHugeManatee/MolSim/sampleConfigs/FallingDropSheet4Task3.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
          
  
  <deltaT>0.0005</deltaT>
  <endTime>5</endTime>
  <dimensions>2</dimensions> 
  <scenarioType>Lennard-Jones-Gravitational</scenarioType> 
  <domainSize x0="303" x1="180" x2="3" />
  <cutoffRadius scaled="1" radius="2.5" />

  <boundaryHandling						
  	top="Reflect" bottom="Reflect"
  	left="Reflect" right="Reflect"		
  	front="Reflect" back="Reflect"
  />
  
  <containerType>CelllistContainer</containerType>
  <epsilon>1</epsilon> 
  <sigma>1</sigma>	
  <gravitationConstant>-12.44</gravitationConstant>
  
 
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/MD_vtk</outputFilePrefix>
  <outputFileType>vtk</outputFileType> 
  <saveLastState>state.state</saveLastState> 
 
  
  <thermostatSwitch>ON</thermostatSwitch>

  <thermostatSettings> 
	<initTemperature>0.5</initTemperature> 
  	<controlInterval>1000</controlInterval>
  </thermostatSettings>
  
 <typeList> 
 <particleType Nr="1" sigma="1.2" epsilon ="1.0"/>
 </typeList>  
 
 <generator>
   <cuboid>
      <bottomLeft x0="1.5" x1="2.0" x2="1.0" />
      <nX x0="250" x1="50" x2="1" />
      <stepWidth>1.2</stepWidth>
      <mass>1</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="0" x2="0"/>
    </cuboid>
  <!--<sphere>
      <center x0="60" x1="25.0" x2="0.0" />
      <radius>2</radius>
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="-20" x2="0"/>
      <brownianMeanVelocity>0.0</brownianMeanVelocity>
    </sphere>-->  
  </generator>
  

</simulationConfig>

=== TheHugeManatee/MolSim/simulationConfig-Plain-WithExplanations.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
<!--(m): mandatory (o): optional-->     
  
  <deltaT></deltaT>
  <endTime></endTime>
  <dimensions></dimensions> <!-- (o) Standrat is 3, For a two dimensionalSimulation all particles should have the same z value > 0  --> 
  <scenarioType></scenarioType> <!-- (m) Possible: Gravitational, Lennard-Jones, Lennard-Jones-Gravitational -->
  <domainSize x0="" x1="" x2="" /><!-- (m) -->
  <cutoffRadius scaled="" radius="" /><!-- (m) scaled implies whether the radius is scaled by the greatest sigma value or not-->

  <boundaryHandling						<!-- (m) Possible: Outflow, Reflect ,Periodic -->
  	top="" bottom=""					<!-- Periodic and Reflect on opposite boundaries doen't work due implementation -->
  	left="" right=""		
  	front="" back=""
  />
  
  <containerType></containerType> <!-- (m) Possible: ParticleContainer , CellListContainer -->
  <epsilon></epsilon> <!-- (m) Default epsilon value (overwritten by type specific values)  -->
  <sigma></sigma>	<!-- (m) Default epsilon value (overwritten by type specific values)  -->
  <gravitationConstant></gravitationConstant> <!-- (o) used in Lennard-Jones-Gravitational, is set to -9.89 if left out -->
  
 
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/MD_vtk</outputFilePrefix>
  <outputFileType>vtk</outputFileType> 
  <saveLastState></saveLastState> <!--(o) for a given filePath the last state of the particles is saved (can be used as inputFile afterwards) -->
  <inputFile></inputFile> <!-- (o)  -->
  
  <thermostatSwitch>ON</thermostatSwitch> <!-- (o) Possible:ON , OFF indicates whether the given thermostat is used. is switched OFF if left out -->

  <thermostatSettings> <!-- (o) if left out thermostatSwitch is set OFF -->
	<initTemperature></initTemperature> <!-- (o) -->
  	<targetTemperature></targetTemperature> <!-- (o) if not used the thermostat tries to keep the starting temperature  -->
  	<controlInterval></controlInterval><!-- (r) the interval the thermostat is applied, it tries to reach the target temperature until the next step -->
  	<estimatedSteps></estimatedSteps> <!-- (o) if used the thermostat tries to reach the temperature until the estimated Time, instead of the next step -->
  	<maxSteps></maxSteps> <!-- (o) time the thermostat stops if not used it runs until end -->
  </thermostatSettings>
  
 <typeList> <!-- (o) a List of types recognized by the particle generator for applying unique values for sigma and epsilon -->
 <particleType Nr="" sigma="" epsilon =""/><!-- (o)  -->
 </typeList>  
 
 <generator>
   <cuboid><!-- (o)  -->
      <bottomLeft x0="" x1="" x2="" />
      <nX x0="" x1="" x2="" />
      <stepWidth></stepWidth>
      <mass></mass>
      <type></type>
      <initialVelocity x0="" x1="" x2=""/>
      <brownianMeanVelocity></brownianMeanVelocity> <!-- (o)  -->
    </cuboid>
  <sphere><!-- (o)  -->
      <center x0="" x1="" x2="" />
      <radius></radius>
      <stepWidth></stepWidth>
      <mass></mass>
      <type></type>
      <initialVelocity x0="" x1="" x2=""/>
      <brownianMeanVelocity></brownianMeanVelocity> <!-- (o)  -->
    </sphere>  
  </generator>
  

</simulationConfig>

=== TheHugeManatee/MolSim/sampleConfigs/bench1000Particle.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
  <deltaT>0.005</deltaT>
  <endTime>10</endTime>
  <scenarioType>Lennard-Jones</scenarioType>
  <domainSize x0="100.0" x1="100.0" x2="20.0" />
  <boundaryHandling
  	top="Outflow" bottom="Outflow"
  	left="Outflow" right="Outflow"
  	front="Outflow" back="Outflow"
  />
  <containerType>ParticleContainer</containerType>
  <epsilon>5</epsilon>
  <sigma>1</sigma>
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/MD_vtk</outputFilePrefix>
  <outputFileType>vtk</outputFileType>
  <cutoffRadius>3.0</cutoffRadius>
  <inputFile></inputFile>

  <generator>
  <!--<sphere>
      <center x0="60" x1="25.0" x2="0.0" />
      <radius>15</radius>
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="-20" x2="0"/>
      <brownianMeanVelocity>0.0</brownianMeanVelocity>
    </sphere>  -->
	 <cuboid>
      <bottomLeft x0="50" x1="50" x2="10" />
      <nX x0="31" x1="31" x2="1" />
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>2</type>
      <initialVelocity x0="0" x1="-10" x2="0"/>
      <brownianMeanVelocity>0.1</brownianMeanVelocity>
   </cuboid>
    
  </generator>
  

</simulationConfig>
