=== TheHugeManatee/MolSim/SimulationConfig.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xse="http://www.codesynthesis.com/xmlns/xml-schema-extension">

  <xsd:simpleType name="TransformType">
  	<xsd:restriction base="xsd:string">
  		<xsd:enumeration value="scale" />
  		<xsd:enumeration value="translate" />
  		<xsd:enumeration value="rotatex0" />
  		<xsd:enumeration value="rotatex1" />
      <xsd:enumeration value="rotatex2" />
      <xsd:enumeration value="shear" />
      <xsd:enumeration value="perspective" />
  	</xsd:restriction>
  </xsd:simpleType> 
       
  <xsd:complexType name="transform">
    <xsd:sequence>
      <xsd:element name="x" type="floatVector" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="type" type="TransformType" use="required" />
    <xsd:attribute name="angle" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear01" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear02" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear10" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear12" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear20" type="xsd:double" use="optional" default="0" />
    <xsd:attribute name="shear21" type="xsd:double" use="optional" default="0" />
  </xsd:complexType>
       
  <xsd:simpleType name="BoundaryConditionType">
  	<xsd:restriction base="xsd:string">
  		<xsd:enumeration value="Outflow" />
  		<xsd:enumeration value="Reflect" />
  		<xsd:enumeration value="Periodic" />
  	</xsd:restriction>
  </xsd:simpleType>    
        
  <xsd:simpleType name="OutputFileType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="xyz" />
      <xsd:enumeration value="vtk" />
    </xsd:restriction>
  </xsd:simpleType>
        
  <xsd:simpleType name="ScenarioType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Gravity"/>
      <xsd:enumeration value="Lennard-Jones"/>
      <xsd:enumeration value="Membrane"/>
      <xsd:enumeration value="Lennard-Jones-Smoothed"/>
</xsd:restriction>
  </xsd:simpleType>    
  
  <xsd:simpleType name="ThermostatSwitch">
  	<xsd:restriction base="xsd:string">
  		<xsd:enumeration value="ON"/>
  		<xsd:enumeration value="OFF"/> 
  	</xsd:restriction>
  </xsd:simpleType>		
  
  <xsd:simpleType name="ContainerType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ParticleContainer"/>
      <xsd:enumeration value="CellListContainer"/>
    </xsd:restriction>
  </xsd:simpleType>     
                       
  <xsd:complexType name="BoundaryHandlingType">
    <xsd:attribute name="right" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="left" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="top" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="bottom" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="front" type="BoundaryConditionType" use="required" />
    <xsd:attribute name="back" type="BoundaryConditionType" use="required" />
  </xsd:complexType>
                            	
	<xsd:complexType name="floatVector">
		<xsd:attribute name="x0" type="xsd:double" use="required"/>
		<xsd:attribute name="x1" type="xsd:double" use="required"/>
		<xsd:attribute name="x2" type="xsd:double" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="intVector">
		<xsd:attribute name="x0" type="xsd:int" use="required"/>
		<xsd:attribute name="x1" type="xsd:int" use="required"/>
		<xsd:attribute name="x2" type="xsd:int" use="required"/>
	</xsd:complexType>   

	<xsd:complexType name="ParticleType">
	  <xsd:attribute name="mass" type="xsd:double" use="required" />
	  <xsd:attribute name="sigma" type="xsd:double" use ="required"/>
	  <xsd:attribute name="epsilon" type="xsd:double" use ="required"/>
	  <xsd:attribute name="isMolecule" type="xsd:boolean" use="optional" default="false" />
	  <xsd:attribute name="averageBondLength" type="xsd:double" use="optional" default="2.2" />
	  <xsd:attribute name="stiffness" type="xsd:double" use="optional" default="300" />
	  <xsd:attribute name="nX0" type="xsd:double" use="optional" default="1" />
	  <xsd:attribute name="nX1" type="xsd:double" use="optional" default="1" />
	  <xsd:attribute name="nX2" type="xsd:double" use="optional" default="1" />
	</xsd:complexType>

	<xsd:complexType name="cutOffRadius">
	  <xsd:attribute name="scaled" type="xsd:boolean" use="required"/>
	  <xsd:attribute name="radius" type="xsd:double" use="required"/>
	</xsd:complexType> 

	<xsd:complexType name ="TypesList">
	  <xsd:sequence>
	    <xsd:element name="particleType" type ="ParticleType" maxOccurs ="unbounded" minOccurs = "1"/>
	  </xsd:sequence>  
	</xsd:complexType> 

<xsd:complexType name="cuboid">
	  <xsd:sequence>
	  	<xsd:element name="bottomLeft" type="floatVector"/>
	  	<xsd:element name="nX" type="intVector" />
	  	<xsd:element name="stepWidth" type="xsd:double"/>
	  	<xsd:element name="type" type="xsd:int"/>
	  	<xsd:element name="initialVelocity" type="floatVector"/>
	  	<xsd:element name="brownianMeanVelocity" type="xsd:double" minOccurs="0" maxOccurs="1"/>
	  	<xsd:element name="transform" type="transform" minOccurs="0" maxOccurs="unbounded" />
	 </xsd:sequence>
  </xsd:complexType>

  
  <xsd:complexType name="sphere">
	  <xsd:sequence>
	  	<xsd:element name="center" type="floatVector"/>
	  	<xsd:element name="radius" type="xsd:int" />
	  	<xsd:element name="stepWidth" type="xsd:double"/>
	  	<xsd:element name="type" type="xsd:int"/>
	  	<xsd:element name="initialVelocity" type="floatVector"/>
	  	<xsd:element name="brownianMeanVelocity" type="xsd:double" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="transform" type="transform" minOccurs="0" maxOccurs="unbounded" />
	 </xsd:sequence>
  </xsd:complexType>

 <xsd:complexType name="cylinder">
	  <xsd:sequence>
	  	<xsd:element name="bottom" type="floatVector"/>
		<xsd:element name="height" type="xsd:int"/>
	  	<xsd:element name="radius" type="xsd:int"/>
	  	<xsd:element name="stepWidth" type="xsd:double"/>
	  	<xsd:element name="type" type="xsd:int"/>
	  	<xsd:element name="initialVelocity" type="floatVector"/>
	  	<xsd:element name="brownianMeanVelocity" type="xsd:double" minOccurs="0" maxOccurs="1"/>
	  	<xsd:element name="transform" type="transform" minOccurs="0" maxOccurs="unbounded" />
	 </xsd:sequence>
 </xsd:complexType>
            
  <xsd:complexType name="generator">
  	<xsd:sequence>
  		<xsd:element name="cuboid" type="cuboid" maxOccurs="unbounded"/>
  		<xsd:element name="sphere" type="sphere" maxOccurs="unbounded"/>
      <xsd:element name="cylinder" type="cylinder" maxOccurs="unbounded"/>
	</xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="ThermostatSettings">
    	<xsd:sequence>
  	  <xsd:element name="initTemperature" type="xsd:double" maxOccurs="1" minOccurs="0" />
  	  <xsd:element name="targetTemperature" type="xsd:double" minOccurs ="0" maxOccurs="1"/>
  	  <xsd:element name="controlInterval" type="xsd:int"/>
  	  <xsd:element name="estimatedSteps" type="xsd:int" minOccurs ="0" maxOccurs="1"/>
	  <xsd:element name="temperaturePerStep" type="xsd:double" minOccurs ="0" maxOccurs="1"/>
	  <xsd:element name="maxSteps" type="xsd:int" minOccurs ="0" maxOccurs="1"/>
	</xsd:sequence> 
 </xsd:complexType>

<xsd:complexType name="forceField">
  <xsd:sequence>
    <xsd:element name="type" type = "xsd:int"/>
    <xsd:element name="from" type="intVector"/>  
    <xsd:element name="to" type="intVector"/>
    <xsd:element name="force" type="floatVector"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="dummyForConstructors">
  <xsd:sequence>
    <xsd:element name="ThermostatSettings" type="ThermostatSettings"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="statistics">
  <xsd:attribute name="fileName" type="xsd:string" use="required" />
  <xsd:attribute name="interval" type="xsd:int" use="required" />  
  <xsd:attribute name="deltaR" type="xsd:double" use="required" />
</xsd:complexType>

<xsd:complexType name="simulationConfig">
    <xsd:sequence>
      <xsd:element name="deltaT" type="xsd:double"/>
      <xsd:element name="endTime" type="xsd:double"/>
      <xsd:element name="dimensions" type="xsd:int" minOccurs="0" maxOccurs="1"/> 
      <xsd:element name="scenarioType" type="ScenarioType"/>
      <xsd:element name="domainSize" type="floatVector" />
      <xsd:element name="cutoffRadius" type="cutOffRadius" />
      <xsd:element name="lRadius" type="xsd:double" minOccurs = "0" maxOccurs = "1"/>      
      <xsd:element name="boundaryHandling" type="BoundaryHandlingType" />
      <xsd:element name="containerType" type="ContainerType" />
      <xsd:element name="gravitation" type="floatVector" minOccurs ="0" maxOccurs="1"/>
      <xsd:element name="outputFrequency" type="xsd:int"/>
      <xsd:element name="disableOutput" type="xsd:boolean"/>
      <xsd:element name="loggerConfigFile" type="xsd:string"/>
      <xsd:element name="outputFilePrefix" type="xsd:string"/>
      <xsd:element name="outputFileIterationOffset" type="xsd:int" minOccurs="0" maxOccurs="1" />
      <xsd:element name="outputFileType" type="OutputFileType"/>
      <xsd:element name="saveLastState" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="inputFile" type="xsd:string" minOccurs ="0" maxOccurs="1"/>
      <xsd:element name="statistics" type="statistics" minOccurs="0" maxOccurs="1" />
      <xsd:element name="thermostatSwitch" type="ThermostatSwitch" minOccurs ="0" maxOccurs="1"/>
      <xsd:element name="thermostatSettings" type="ThermostatSettings" minOccurs ="0" maxOccurs="1"/>      
      <xsd:element name="typeList" type="TypesList" />
      <xsd:element name="forceField" type="forceField" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="generator" type="generator"/>
  </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="simulationConfig" type="simulationConfig" />

</xsd:schema>

=== TheHugeManatee/MolSim/sampleConfigs/sheet5_membrane.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
<!--(m): mandatory (o): optional-->     
  
  <deltaT>0.01</deltaT>
  <endTime>150</endTime>
  <dimensions>3</dimensions> <!-- (o) Standard is 3, For a two dimensionalSimulation all particles should have the same z value > 0  --> 
  <scenarioType>Membrane</scenarioType> <!-- (m) Possible: Gravitational, Lennard-Jones, Membrane  -->
  <domainSize x0="148" x1="148" x2="148" /><!-- (m) -->
  <cutoffRadius scaled="1" radius="4.0" /><!-- (m) scaled implies whether the radius is scaled by the greatest sigma value or not-->

  <boundaryHandling
  	top="Periodic" bottom="Periodic"					
  	left="Periodic" right="Periodic"		
  	front="Reflect" back="Reflect"
  />
  
  <containerType>CellListContainer</containerType> <!-- (m) Possible: ParticleContainer , CelllistContainer -->
  <gravitation x0="0" x1="0" x2="-0.001" /> <!-- (o) -->
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/Membrane_part1_</outputFilePrefix>
  <outputFileType>vtk</outputFileType> 
  <saveLastState>state.state</saveLastState> <!--(o) for a given filePath the last state of the particles is saved (can be used as inputFile afterwards) -->
  <inputFile></inputFile> <!-- (o)  -->
  
  <thermostatSwitch>OFF</thermostatSwitch> <!-- (o) Possible:ON , OFF indicates whether the given thermostat is used. is switched OFF if left out -->


  
 <typeList> <!-- (m) a List of types recognized by the particle generator for applying unique values for sigma and epsilon -->
 <particleType 
 		sigma="1" 
 		epsilon="1"
 		mass="1"  
 		isMolecule="true" 
 		stiffness="300" 
 		averageBondLength="2.2" 
 		/>
 </typeList>  
 <forceField>
   <type>0</type> 
   <from x0="17" x1="24" x2="0" />
   <to x0="18" x1="25" x2="0" />
   <force x0="0" x1="0" x2="0.8" />
 </forceField>
 
 <generator>
  <cuboid><!-- (o)  -->
    <bottomLeft x0="15" x1="15" x2="1.5" />
    <nX x0="50" x1="50" x2="1" />
    <stepWidth>2.2</stepWidth>
    <type>0</type>
    <initialVelocity x0="0" x1="0" x2="0"/>
  </cuboid>
</generator>

</simulationConfig>

=== TheHugeManatee/MolSim/sampleConfigs/drop.xml
<?xml version="1.0"?>

<simulationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulationConfig.xsd">
       
  <deltaT>0.00005</deltaT>
  <endTime>10</endTime>
  <scenarioType>Lennard-Jones</scenarioType>
  <domainSize x0="120.0" x1="50.0" x2="2" />
  <boundaryHandling
  	top="Reflect" bottom="Reflect"
  	left="Reflect" right="Reflect"
  	front="Reflect" back="Reflect"
  />
  <containerType>CelllistContainer</containerType>
  <epsilon>5</epsilon>
  <sigma>1</sigma>
  <outputFrequency>100</outputFrequency>
  <disableOutput>0</disableOutput>
  <loggerConfigFile>Logger.properties</loggerConfigFile>
  <outputFilePrefix>OutputFiles/MD_vtk</outputFilePrefix>
  <outputFileType>vtk</outputFileType>
  <cutoffRadius>3.0</cutoffRadius>
  <inputFile></inputFile>

  <generator>
  <sphere>
      <center x0="60" x1="25.0" x2="0.0" />
      <radius>15</radius>
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>1</type>
      <initialVelocity x0="0" x1="-20" x2="0"/>
      <brownianMeanVelocity>0.0</brownianMeanVelocity>
    </sphere>  
	 <!--<cuboid>
      <bottomLeft x0="5" x1="10" x2="15" />
      <nX x0="50" x1="4" x2="10" />
      <stepWidth>1.1225</stepWidth>
      <mass>1</mass>
      <type>2</type>
      <initialVelocity x0="0" x1="-10" x2="0"/>
      <brownianMeanVelocity>0.1</brownianMeanVelocity>
   </cuboid>-->
    
  </generator>
  

</simulationConfig>
